[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Redirections pour SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Pour les assets statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"